name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.0=py313hfc0e8ea_101
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=24.1.0=py313h06a4308_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=25.3.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.1.3=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=44.0.1=py313h7825ff9_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.7.7=hfab0078_0
  - libcurl=8.12.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.0=py313h06a4308_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py313h06a4308_1
  - rich=13.9.4=py313h06a4308_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - setuptools=78.1.1=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.67.1=py313h7040dfc_0
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - urllib3=2.3.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.2
      - amqp==5.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asyncssh==2.21.0
      - atpublic==5.1
      - attrs==25.3.0
      - billiard==4.2.1
      - biobricks==0.3.9
      - blinker==1.9.0
      - boto3==1.38.8
      - botocore==1.38.8
      - celery==5.5.2
      - chardet==5.2.0
      - click==8.1.8
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - cloup==3.0.7
      - colorama==0.4.6
      - configobj==5.0.9
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2025.4.1
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distributed==2025.4.1
      - dpath==2.2.0
      - dulwich==0.22.8
      - dvc==3.59.1
      - dvc-data==3.16.10
      - dvc-http==2.32.0
      - dvc-objects==5.1.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.21.0
      - dvc-task==0.40.2
      - einops==0.8.1
      - einx==0.3.0
      - entrypoints==0.4
      - filelock==3.18.0
      - flask==3.1.0
      - flatten-dict==0.4.2
      - flufl-lock==8.1.0
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - funcy==2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grandalf==0.8
      - gto==1.7.2
      - gunicorn==23.0.0
      - hydra-core==1.3.2
      - iterative-telemetry==0.0.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - kombu==5.5.3
      - lion-pytorch==0.2.3
      - locket==1.0.0
      - loguru==0.7.3
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - networkx==3.4.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - orjson==3.10.18
      - pandas==2.2.3
      - partd==1.4.2
      - pathspec==0.12.1
      - pillow==11.2.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - psutil==7.0.0
      - psycopg==3.2.7
      - pubchempy==1.0.4
      - py4j==0.10.9.7
      - pyarrow==20.0.0
      - pydot==4.0.0
      - pygit2==1.18.0
      - pygtrie==2.5.0
      - pyparsing==3.2.3
      - pyspark==3.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2024.9.6
      - reportlab==4.4.0
      - rotary-embedding-torch==0.8.6
      - s3transfer==0.12.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scmrepo==3.3.11
      - seaborn==0.13.2
      - selfies==2.2.0
      - semver==3.0.4
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sqltrie==0.11.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tblib==3.1.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tornado==6.4.2
      - triton==3.3.0
      - typer==0.15.3
      - tzdata==2025.2
      - vine==5.1.0
      - voluptuous==0.15.2
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - x-transformers==2.3.11
      - yarl==1.20.0
      - zc-lockfile==3.0.post1
      - zict==3.0.0
prefix: /home/ubuntu/miniconda3
